<?php
return array (
	'post-formats' => array (),
	'post-thumbnails' => array (),
	'custom-background' => array (
		'enabled' => '0',
		'default-image' => '',
		'default-position-x' => 'left',
		'default-repeat' => 'no-repeat',
		'default-attachment' => 'scroll',
		'default-color' => '',
		'wp-head-callback' => '',
		'admin-head-callback' => '',
		'admin-preview-callback' => '',
	),
	'custom-header' => array (
		'enabled' => '0',
		'default-image' => '',
		'random-default' => '0',
		'width' => '',
		'height' => '',
		'flex-width' => '0',
		'flex-height' => '0',
		'default-text-color' => '',
		'header-text' => '1',
		'uploads' => '1',
		'wp-head-callback' => '',
		'admin-head-callback' => '',
		'admin-preview-callback' => '',
	),
	'automatic-feed-links' => '0',
	'html5' => array (
		'comment-list' => '0',
		'comment-form' => '0',
		'search-form' => '0',
	),
	'sidebars' => array (),
	'menus' => array (),
	'editor-style' => ''
);